root: true

extends:
  - '@form8ion'
  - '@form8ion/vitest'
  - '@form8ion/cucumber'

rules:
  depend/ban-dependencies: warn

overrides:
  - files: example.js
    rules:
      no-unused-expressions: off
  - files: "example.js"
    rules:
      "import/no-unresolved":
        - error
        - ignore:
            - "yargs/helpers"
