root: true

extends:
  - '@form8ion'
  - '@form8ion/cucumber'

rules:
  import/extensions:
    - error
    - ignorePackages

overrides:
  - files: example.js
    rules:
      no-unused-expressions: off
